### ISSUE TITLE
Create Repository#all_issues Method

### ISSUE THREAD

**Issue by runpaint** [fcoury/octopi#18]
Given that my [request to return all issues in a single API call](http://github.com/develop/develop.github.com/issues#issue/16) has been marked 'possibly', we need a .all_issues method for Repository objects, so clients don't have to enumerate states.

**Comment by xiongchiamiov** [comment]
So, I thought that simply adding `:state => state` to the call to Octopi::Issue#find_all in repository.rb would make this actually work (since otherwise, the requested state is completely ignored).  I'm finding, though, that what I get is the same (open) issue twice, rather than my one open issue and my one closed issue. :/

It's 4 in the morning, though, so I think I should be off to bed.  I'll try and take a proper look at it when I'm a bit more clear-headed.

**Comment by xiongchiamiov** [comment]
So, I wasn't actually installing the new modified gem... yeah.  I implemented what I was talking about in 8edd5fcc7373727537b97f072c355706e93d9169

**Comment by xiongchiamiov** [comment]
As I noted in the comments on the aforementioned commit, I made/fixed tests for this in 86c17cd587922304ff75d53290d01ceed1eef630 .

**Comment by jeffWelling** [comment]
I noticed that Octopi hasn't seen any activity in almost 2 months. Is it still actively maintained?
Is this something that you are planning on implementing, or are developers working with Octopi expected to code around it?

**Comment by radar** [comment]
This is now fixed in 4dbfe0c.
